c:\arduino\hardware\tools\avr\bin\avr-g++ -x c++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\troyka.cpp -otroyka.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-g++ -x c++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\terr.ino -oterr.ino.o
c:\arduino\hardware\tools\avr\bin\avr-gcc -c -g -Os -Wall -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\hooks.c -ohooks.c.o
c:\arduino\hardware\tools\avr\bin\avr-gcc -c -g -Os -Wall -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\WInterrupts.c -oWInterrupts.c.o
c:\arduino\hardware\tools\avr\bin\avr-gcc -c -g -Os -Wall -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\wiring.c -owiring.c.o
c:\arduino\hardware\tools\avr\bin\avr-gcc -c -g -Os -Wall -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\wiring_analog.c -owiring_analog.c.o
c:\arduino\hardware\tools\avr\bin\avr-gcc -c -g -Os -Wall -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\wiring_digital.c -owiring_digital.c.o
c:\arduino\hardware\tools\avr\bin\avr-gcc -c -g -Os -Wall -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\wiring_pulse.c -owiring_pulse.c.o
c:\arduino\hardware\tools\avr\bin\avr-gcc -c -g -Os -Wall -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\wiring_shift.c -owiring_shift.c.o
c:\arduino\hardware\tools\avr\bin\avr-g++ -x c++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\abi.cpp -oabi.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-g++ -x c++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\CDC.cpp -oCDC.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-g++ -x c++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\HardwareSerial.cpp -oHardwareSerial.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-g++ -x c++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\HardwareSerial0.cpp -oHardwareSerial0.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-g++ -x c++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\HardwareSerial1.cpp -oHardwareSerial1.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-g++ -x c++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\HardwareSerial2.cpp -oHardwareSerial2.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-g++ -x c++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\HardwareSerial3.cpp -oHardwareSerial3.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-g++ -x c++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\IPAddress.cpp -oIPAddress.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-g++ -x c++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\main.cpp -omain.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-g++ -x c++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\new.cpp -onew.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-g++ -x c++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\PluggableUSB.cpp -oPluggableUSB.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-g++ -x c++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\Print.cpp -oPrint.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-g++ -x c++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\Stream.cpp -oStream.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-g++ -x c++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\Tone.cpp -oTone.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-g++ -x c++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\USBCore.cpp -oUSBCore.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-g++ -x c++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\WMath.cpp -oWMath.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-g++ -x c++ -c -g -Os -Wall -fno-exceptions -ffunction-sections -fdata-sections -mmcu=atmega328p -DF_CPU=16000000L -MMD -DUSB_VID=null -DUSB_PID=null -DARDUINO=105 -Ic:\arduino\hardware\arduino\avr\cores\arduino -Ic:\arduino\hardware\arduino\avr\variants\standard c:\arduino\hardware\arduino\avr\cores\arduino\WString.cpp -oWString.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\hooks.c.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\WInterrupts.c.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\wiring.c.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\wiring_analog.c.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\wiring_digital.c.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\wiring_pulse.c.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\wiring_shift.c.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\abi.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\CDC.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\HardwareSerial.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\HardwareSerial0.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\HardwareSerial1.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\HardwareSerial2.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\HardwareSerial3.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\IPAddress.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\main.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\new.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\PluggableUSB.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\Print.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\Stream.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\Tone.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\USBCore.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\WMath.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-ar rcs C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\WString.cpp.o
c:\arduino\hardware\tools\avr\bin\avr-gcc -Os -Wl,--gc-sections -mmcu=atmega328p -oC:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\terr.ino.elf C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\troyka.cpp.o C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\terr.ino.o C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\core.a -LC:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build -lm
c:\arduino\hardware\tools\avr\bin\avr-objcopy -O ihex -j .eeprom --set-section-flags=.eeprom=alloc,load --no-change-warnings --change-section-lma .eeprom=0 C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\terr.ino.elf C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\terr.ino.eep
c:\arduino\hardware\tools\avr\bin\avr-objcopy -O ihex -R .eeprom C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\terr.ino.elf C:\Users\out-chervyakov-sg\IdeaProjects\TerraPia\tst\build\terr.ino.hex
                   